version: '2.4'

services:
  duckdns:
    image: maksimstojkovic/duckdns
    container_name: duckdns
    environment:
      - DUCKDNS_TOKEN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      - DUCKDNS_DOMAIN=test.duckdns.org
      - DUCKDNS_DELAY=5 #optional
    restart: unless-stopped

  letsencrypt:
    image: maksimstojkovic/letsencrypt
    container_name: letsencrypt
    volumes:
      - ./certs:/etc/letsencrypt
    environment:
      - DUCKDNS_TOKEN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      - DUCKDNS_DOMAIN=test.duckdns.org
      - LETSENCRYPT_DOMAIN= #optional
      - LETSENCRYPT_WILDCARD=false #optional
      - LETSENCRYPT_EMAIL= #optional
      - TESTING=false #optional
      - UID=0 #optional
      - GID=0 #optional
    restart: unless-stopped
